language: java
jdk:
- oraclejdk14
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

deploy:
  provider: heroku
  app:
    master: psa-soporte
  api_key:
    secure: hgd538E1QPltePbsN5MkerYvKcTnzvW7GDD7vq7lzDdrXKXQWxqaKxLk19SHOlxD9F45+GWueEovOthdwRW2I5cKXC8b0/9rD4piKbu0zMllFFCLkdZ9QsMEjfb5nXMG+ps5jnzuRpg+fOsRhI3CM8kWRmNptqm/lRDZlZ5TApdPzOjdx6MuDpmCGCEnM8UFeRbvphrTIPJF9kcXI1ySi/irG6X0R5KYXcKemn85a3v7tmtys2AL4SlilRgNO20/mc4Hduh4/6LyKt+stW03IEzeMGP0mCAu4FNnLrKkvlxYe4X8LlD9dE+8ll3HsrC02bt04hjWhUCkgKZPBVC+MiwaPoQ+IdDEsXklOOdBWfjJFv+7OsqIhOaJ8MbdkDYiv3g0JzfOnKj7VaWJD/1uD/o7c4MWhhk0gmnc8vjFzzvdPV5g3NkZcSJpfUO35+KSBBFUig9Zl1njECfKoNm+7fmKcWT1kM6dDtRxaznY06SziztgS7aZZXcsUbR2ykq35uxQiGaa6iZE3KIQq2aYUXWCuPn0yjH2JzWpNJ+MegZwiDPld4YQyPyCPvAHVkjH/d6pba7fYtdNZhMC37vdW1kl6En5Rc6Pf1/Qum1p56qvnnyW0rdc6C65J44g/wpnoa4ZFQimB3PWlTvs2nkeIw040PH+IegAa6eiF7RXPyU=
